# Data Collection

## Business Purpose

Basket CDS pricing requires market data from multiple reference entities.

In this project, five major U.S. banks are selected as reference names:

- JPMorgan Chase (JPM)
- Bank of America (BAC)
- Citigroup (C)
- Goldman Sachs (GS)
- Morgan Stanley (MS)

Historical stock prices are collected as a proxy for estimating credit dependence among reference entities.

## Objective

The objective of this notebook is to:

1. Collect historical market data
2. Validate data quality
3. Store cleaned data for future analysis

## Step 1: Import Libraries

### Purpose

This step imports the Python libraries required for data collection and analysis.

- yfinance: download historical market data
- pandas: data manipulation
- numpy: numerical calculations

In [4]:
import yfinance as yf
import pandas as pd
import numpy as np

## Step 2: Select Reference Entities

### Purpose

Basket CDS pricing requires multiple reference entities.

Five large U.S. financial institutions are selected because:

- They are systemically important banks
- Historical market data is readily available
- Their credit risk is economically related

In [5]:
banks = [
    "JPM",   # JPMorgan Chase
    "BAC",   # Bank of America
    "C",     # Citigroup
    "GS",    # Goldman Sachs
    "MS"     # Morgan Stanley
]

banks

['JPM', 'BAC', 'C', 'GS', 'MS']

## Step 3: Download Historical Market Data

### Purpose

Historical stock prices are used as a proxy for measuring co-movement among institutions.

The data will later be used to estimate:

- Pearson correlation
- Rank correlation
- Default dependence structure

In [7]:
prices = yf.download(
    banks,
    start="2023-01-01",
    end="2025-01-01",
    auto_adjust=True
)

prices.head()

[*********************100%***********************]  5 of 5 completed

Price           Close                                                \
Ticker            BAC          C          GS         JPM         MS
Date
2023-01-03  30.640949  40.644218  318.011597  123.735207  76.617455
2023-01-04  31.217012  41.691841  319.371124  124.889008  77.448700
2023-01-05  31.152998  41.505405  315.752106  124.861366  76.796211
2023-01-06  31.463890  42.002571  319.720154  127.250633  78.262054
2023-01-09  30.988411  42.206779  324.239227  126.724785  78.333572

Price            High                                                ...  \
Ticker            BAC          C          GS         JPM         MS  ...
Date                                                                 ...
2023-01-03  31.171293  41.505401  320.197690  125.218720  77.404005  ...
2023-01-04  31.838793  42.206776  321.768461  126.079462  78.074365  ...
2023-01-05  31.217004  41.691846  317.019674  125.193469  77.019664  ...
2023-01-06  31.619337  42.339939  320.565209  127.656539  78.619580  ...
2023-01-09  31.783922  42.899275  327.454064  128.117779  79.468716  ...

Price            Open                                                  Volume  \
Ticker            BAC          C          GS         JPM         MS       BAC
Date
2023-01-03  30.384923  40.617585  317.350258  123.845105  76.545948  35221500
2023-01-04  30.997563  41.318960  319.674225  124.531868  76.465510  41998500
2023-01-05  31.015839  41.461015  316.202174  125.147341  76.778338  34177000
2023-01-06  31.171288  41.780617  319.003705  125.580898  77.260991  34068700
2023-01-09  31.774780  42.517514  323.210484  127.859479  78.878797  43818800

Price
Ticker             C       GS       JPM       MS
Date
2023-01-03  19564000  1589700  11054800  5108900
2023-01-04  21507200  1881000  11687600  7726800
2023-01-05  12314900  1397800   8381300  5339900
2023-01-06  16736300  3097800  10029100  5710900
2023-01-09  16745500  1989000   8482300  5039700

[5 rows x 25 columns]

## Step 4 Extract Adjusted Closing Prices

The downloaded dataset contains multiple variables, including Open, High, Low, Close, and Volume.

For correlation estimation, only adjusted closing prices are required.

These prices will later be converted into daily returns.

In [8]:
close_prices = prices["Close"]

close_prices.head()

Ticker            BAC          C          GS         JPM         MS
Date
2023-01-03  30.640949  40.644218  318.011597  123.735207  76.617455
2023-01-04  31.217012  41.691841  319.371124  124.889008  77.448700
2023-01-05  31.152998  41.505405  315.752106  124.861366  76.796211
2023-01-06  31.463890  42.002571  319.720154  127.250633  78.262054
2023-01-09  30.988411  42.206779  324.239227  126.724785  78.333572

## Step 5 Data Quality Assessment

Before performing any quantitative analysis, the dataset is checked for:

- missing observations,
- dataset dimensions,
- data completeness.

High-quality data is essential because missing values may bias correlation estimates and Monte Carlo simulations.

In [9]:
print("Dataset Shape:")
print(close_prices.shape)

print("\nMissing Values:")
print(close_prices.isna().sum())

Dataset Shape:
(502, 5)

Missing Values:
Ticker
BAC    0
C      0
GS     0
JPM    0
MS     0
dtype: int64

## Step 6 Save Processed Dataset

The cleaned adjusted closing prices are saved locally.

Saving intermediate datasets improves reproducibility and allows subsequent notebooks to load the same data without repeating the download process.

In [10]:
close_prices.to_csv("../Data/bank_prices.csv")

## Step 7 Verify Saved Dataset

The saved CSV file is reloaded to verify that the export was successful.

In [11]:
saved_data = pd.read_csv("../Data/bank_prices.csv")

saved_data.head()

         Date        BAC          C          GS         JPM         MS
0  2023-01-03  30.640949  40.644218  318.011597  123.735207  76.617455
1  2023-01-04  31.217012  41.691841  319.371124  124.889008  77.448700
2  2023-01-05  31.152998  41.505405  315.752106  124.861366  76.796211
3  2023-01-06  31.463890  42.002571  319.720154  127.250633  78.262054
4  2023-01-09  30.988411  42.206779  324.239227  126.724785  78.333572

# Summary

In this notebook, historical adjusted closing prices for five major U.S. banks were collected and saved for future analysis.

Completed tasks:

- Imported required libraries
- Selected five reference entities
- Downloaded historical market data
- Extracted adjusted closing prices
- Performed basic data quality checks
- Saved the processed dataset

The next notebook will estimate default probabilities and hazard rates, providing the foundation for the Basket CDS pricing model.